### ISSUE TITLE
Update code of conduct

### ISSUE THREAD

**Issue by mdboom** [matplotlib/governance#2]
We should probably pick one of the following as a starting point:
- [JupyterDay](https://github.com/jupyter/governance/blob/master/CodeofConductJupyterDay.md)
- [Scipy](http://scipy2016.scipy.org/ehome/146062/388087/)
- [PyCon](https://github.com/python/pycon-code-of-conduct/blob/master/code_of_conduct.md)

These are all fairly geared toward in-person interactions (though not exclusively by any means).  One more appropriate perhaps for online interactions is:
- [Python Community Code of Conduct](https://www.python.org/psf/codeofconduct/)

**Comment by tacaswell** [comment]
https://github.com/jupyter/governance/pull/23 as reference as well.
