### ISSUE TITLE
Move the communication guidelines to the (future) development guide repo

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/governance#24]
waiting on https://github.com/matplotlib/matplotlib/issues/22866

It is simpler if all of the content in this repo is content that requires sign off from a majority of the steering council to change.  

We want to be more agile/have less ceremony on the communication guidelines.

**Comment by story645** [comment]
> We want to be more agile/have less ceremony on the communication guidelines

what do you mean by this?

**Comment by tacaswell** [comment]
Correct, the governance has a process for changing it self which has high level of ceremony and sign off (because changing the governance should be a rare-ish thing) vs the communication guidelines which I would put on the same footing as the PR review guidance or development guide which we want to be able to be able to update as we need.

Rather than having to on a case-by-case basis having to decide if the PR to this repo needs the higher level of scrutiny, I want to remove anything that does not need it that level.
